### ISSUE TITLE
Endpoint not found: /external-api/auth

### ISSUE THREAD

**Issue by fernandomg** [monerium/sdk#34]
After I enter the credentials for the user by following the steps in the "authorization code flow", I'm redirected to `external-/api/auth` and get the following error.

I instantiated `MoneriumClient` with the `'sandbox'` parameter.

```json
{
  "code": 404,
  "status": "Not Found",
  "message": "Endpoint not found: /external-api/auth",
  "details": {
    "id": "/external-api/auth",
    "method": "GET",
    "resource": "endpoint"
  }
}
```

the code:
```ts
    const authFlowUrl = client.getAuthFlowURI({
      client_id: MONERIUM_DATA.client_id,
      redirect_uri: 'http://localhost:3000/test',
    })

    window.location.replace(authFlowUrl)
```

Am I doing something wrong?

**Comment by einaralex** [comment]
I can't see that you are doing anything wrong. Could you show me how you initiate the client and what `authFlowUrl` gets?

I'm working on an example here, this might help!
https://github.com/monerium/sdk-template

**Comment by fernandomg** [comment]
Thanks for the reply Einar.

Here's the value for `authFlowUrl`: `https://api.monerium.dev/auth?client_id=7765e3f9-e049-11ed-b84d-4a06a529d389&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Ftest&code_challenge=TbIR-DnbBJQhXQXK4DIRrm6nToDX56n7FBkrwAthx6g&code_challenge_method=S256&response_type=code`

and the single line to initialize the client:
```ts
const client = new MoneriumClient('sandbox')
```

**Comment by einaralex** [comment]
What version are you on?

**Comment by fernandomg** [comment]
my dependency is `"@monerium/sdk": "^2.0.18"` and the version installed: `"version": "2.0.18"`

I don't know if it is worth mentioning that I created the app using my sandbox account, but I don't know if I'm a partner or need to do something to be a "sandbox partner".

**Comment by einaralex** [comment]
So if you visit the url you sent me: https://api.monerium.dev/auth?client_id=7765e3f9-e049-11ed-b84d-4a06a529d389&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Ftest&code_challenge=TbIR-DnbBJQhXQXK4DIRrm6nToDX56n7FBkrwAthx6g&code_challenge_method=S256&response_type=code

You'll see that there is a error in the query params which says, no such client id.

You have to create an app and use the auth flow client id that will be provided to you there: https://monerium.dev/docs/getting-started/create-app

**Comment by fernandomg** [comment]
Just checked the app I registered and the "auth flow client id" that I'm sending is right.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3315606/234208164-54ed4d9b-f119-447e-893a-545f1376f995.png">

The steps that I followed:
1. create an account in `sandbox.monerium.dev`
2. create an app
3. use the clientId in the `getAuthFlowURI` call

---

To be sure there's no issue related to the sandbox account, I just created an app with my regular account, same result: `https://sandbox.monerium.dev/login?error=server_error&error_description=No+such+client+ID`

`authFlowUrl`: `https://api.monerium.dev/auth?client_id=7a1f020d-e33d-11ed-865f-ae2bd580299a&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Ftest&code_challenge=OYmSChRsykzMlXJ5OfU_qtyGo0NEJMMOm_7MlxVXwYw&code_challenge_method=S256&response_type=code`

---

**Comment by einaralex** [comment]
Are you sure you are passing the correct client Id to the getAuthFlowURI?
Because the client_id in the authFlowUrl should be the same as the clientId you pass to getAuthFlowURI.

If you replace the client_id with the Authorization Code Flow clientId, you get the correct result:
https://api.monerium.dev/auth?client_id=77643a5c-e049-11ed-b84d-4a06a529d389&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Ftest&code_challenge=OYmSChRsykzMlXJ5OfU_qtyGo0NEJMMOm_7MlxVXwYw&code_challenge_method=S256&response_type=code


A working code example here: [Codesandbox](https://codesandbox.io/s/eloquent-dust-wmw6db?file=/src/App.js)

**Comment by fernandomg** [comment]
ohhhhhhhhhhh 🤦 

It worked like a charm, I was using the `Client Credentials Authorization`.

Holly...

Thank you so much for your patience and help. And sorry for the noise.

**Comment by einaralex** [comment]
Glad its solved :D Let me know if there is anything else I can help you with :)
