### ISSUE TITLE
network and chain props are not included in the type

### ISSUE THREAD

**Issue by arnigudj** [monerium/sdk#35]
**Describe the bug**
I'm using the linkAddress method to connect a Safe to Monerium on the Gnosis chain, but the network and chain props are not included [in the type](https://github.com/monerium/sdk/blob/4d47d6fe4e798e8af61eab7dd03b188322fd0f31/src/types.ts#L340-L345).

**To Reproduce**
Try using the following code

```js
if (!isSafeAddressLinked) {
  await this.#client.linkAddress(authContext.defaultProfile, {
    address: safeAddress,
    message: SIGNATURE_MESSAGE,
    signature: '0x',
    // @ts-expect-error - network and chain are not defined in the type and mandatory for multisig (signature 0x)
    network: await this.#client.getNetwork(),
    chain: await this.#client.getChain(),
    accounts: [{
      network: await this.#client.getNetwork(),
      chain: await this.#client.getChain(),
      currency: Currency.eur
    }]
  })
}
```

**Expected behavior**
network and chain to be added in the type.

**Additional context**

* [API documentation - add address](https://monerium.dev/api-docs#operation/profile-addresses)

**Comment by einaralex** [comment]
✅
