### ISSUE TITLE
Can't import `constants` from `@monerium/sdk`

### ISSUE THREAD

**Issue by fernandomg** [monerium/sdk#97]
**Describe the bug**
I tried to import `constants` from `@monerium/sdk` as stated in the [release notes](https://github.com/monerium/sdk/releases/tag/v2.3.0), but it's not working.

**To Reproduce**

1. install the latest SDK version from npm
2. write `import { constants } from '@monerium/sdk'`
3. I get the error `TS2305: Module '"@monerium/sdk"' has no exported member 'constants'.`

**Expected behavior**
To be able to import the `constants`.

**Additional context**
Maybe the export needs to be done in the same way that it's done for the utils?
https://github.com/monerium/sdk/blob/main/src/index.ts#L3-L4

**Comment by einaralex** [comment]
Could you confirm that you are using an up-to-date version of the SDK?
I just tried in a [CodeSandbox](https://codesandbox.io/s/gallant-nash-gzzvr8?file=/src/App.js), and it seems to work.

If that doesn't work, please provide me some info on the environment you're working with, frameworks and such.

**Comment by fernandomg** [comment]
It's a NextJS app. But it seems to happen at the editor level because when consuming it the value is displayed.

<img width="1421" alt="image" src="https://github.com/monerium/sdk/assets/3315606/aa89efed-b24a-48a5-a723-00581fba0a1c">

You can check it here: https://codesandbox.io/p/sandbox/currying-wave-g4hmx5

**Comment by einaralex** [comment]
Ahh ok it's not properly typed, thank you!

**Comment by einaralex** [comment]
It's fixed in 2.6, just so you know, the Chain and Network enums have been removed. 

Typescript does not like when you try to export enums and consts together and the naming was also conflicting with the types.
