### ISSUE TITLE
`getBalance` and API balances return type mismatch

### ISSUE THREAD

**Issue by fernandomg** [monerium/sdk#98]
**Describe the bug**
The return type for the [`getBalance`](https://github.com/monerium/sdk/blob/61f0bab5cb39bca8e512dc062f6c67ab903e606c/src/client.ts#L110) method is `Promise<Balances> | Promise<Balances[]>` while the return type for the [/balances API](https://monerium.dev/api-docs#operation/profile-balances) is always an array.

**Expected behavior**
The return type must always be `Balances[]`

**Comment by einaralex** [comment]
Greatly appreciate the reports 🙏
